services:
  sensation-db:
    image: postgres:15
    container_name: sensation-postgres
    restart: unless-stopped
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensation
#    это нужно для файла который на сервере
#    volumes:
#      - ./data:/var/lib/postgresql/data
#      - ./backups:/backups

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9433:80"